//TODO: Implement deadzone rescaling

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     GrabEndpoint,   sensorTouch)
#pragma config(Motor,  motorA,          Mimic1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Mimic2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Grabber,       tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Arm1,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm2,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Base,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-sensormux.h"

const float mimicArmConvert = 40.0/24.0;
const float Arm2Convert = 2550.0/90.0;
//1 degree of rotation is 40/24 encoderTicks for arm2mimic
//1 degree of rotation is 2550/90 encoderTicks for the arm2

const int reInitializeBtn = 6;
const int baseLeftBtn = 7;
const int baseRightBtn = 8;
const int grabberToggleBtn = 1;
const int modeSwitchBtn = 10;

float Arm1MimicValue;
float Arm2MimicValue;
float Arm1Encoder;
float Arm2Encoder;
float GrabberEncoderValue;

bool lastGrabberStatus;
bool grabberStatus;
bool grabberOpen = true;

bool lastModeSwitchStatus;
bool modeSwitchStatus;
bool inMimicMode = true;

void getMimicValues(){
	Arm1MimicValue = nMotorEncoder[Mimic1]/mimicArmConvert;
	Arm2MimicValue = -nMotorEncoder[Mimic2]/mimicArmConvert;
	Arm1Encoder = nMotorEncoder[Arm1];
	Arm2Encoder = nMotorEncoder[Arm2]/Arm2Convert;
	GrabberEncoderValue = nMotorEncoder[Grabber];
	lastGrabberStatus = grabberStatus;
	grabberStatus = SensorValue[GrabEndpoint] == 1;
}

void updateBasedOnMimic(){
	float Arm2Error = Arm2MimicValue - Arm2Encoder;
	motor[Arm2] = Arm2Error;

	float Arm1Error = Arm1MimicValue - Arm1Encoder;
	motor[Arm1] = Arm1Error;
}

void updateBasedOnJoystick(){
	int y1Val,y2Val;
	getJoystickSettings(joystick);
	y1Val = joystick.joy1_y1;
	y2Val = joystick.joy1_y2;

	motor[Arm1] = abs(y1Val) > 10 ? y1Val/10 : 0;
	motor[Arm2] = abs(y2Val) > 10 ? -y2Val/10 : 0;

	lastGrabberStatus = grabberStatus;
	grabberStatus = joy1Btn(grabberToggleBtn);
}

void updateGrabberPosition(){
	if(!lastGrabberStatus && grabberStatus)
		grabberOpen = !grabberOpen;

	if(grabberOpen)
		grabberError = 10 - GrabberEncoderValue;
	else
		grabberError = -60 - GrabberEncoderValue ;

	if(abs(grabberError) > 10)
		motor[Grabber] = grabberError > 0 ? 50:-50;
	else
		motor[Grabber] = 0;
}

void updateGeneric(){
	if(joy1Btn(baseLeftBtn))
		motor[Base] = 5;
	else if(joy1Btn(baseRightBtn))
		motor[Base] = -5;
	else
		motor[Base] = 0;

	if(joy1Btn(reInitializeBtn))
		initialize();
		
	updateGrabberPosition();
}

void modeSwitchCheck(){
	lastModeSwitchStatus = modeSwitchStatus;
	modeSwitchStatus = joy1Btn(modeSwitchBtn);

	if(!lastModeSwitchStatus && modeSwitchStatus)
		inMimicMode = !inMimicMode;

}

void initialize(){
	nMotorEncoder[Mimic1] = 0;
	nMotorEncoder[Mimic2] = 0;
	nMotorEncoder[Arm1] = 0;
	nMotorEncoder[Arm2] = 0;
	nMotorEncoder[Grabber] = 0;
	nNoMessageCounterLimit = 150;
}

task main(){
	initialize();
	while (true)
	{
		getMimicValues();
		if(inMimicMode)
			updateBasedOnMimic();
		else
			updateBasedOnJoystick();
		updateGeneric();
		modeSwitchCheck();
	}
}
